export const slides=[];
const S=(title,img,blocks,formula,notes,opts={})=>slides.push({title,img,blocks,formula,notes,...opts});
S('ShiroFOC hardware design','overview',[
['A single-axis FOC servo module','Topology, component choices and the measurements that establish the operating envelope.'],
['A1 drawing / A0 electrical design','16 September 2026\n36 review slides + 5 technical appendices']
],'Schematic design review',
'ShiroFOC closes motor-control loops locally and communicates with a coordinating motherboard over CAN. This presentation follows the current connected KiCad redraw. It explains the released circuit, documented calculations and engineering tradeoffs. The schematic is ready for first-prototype PCB layout. It is not a fabrication release or a hardware qualification. Current and thermal values remain design targets.',{cover:true});
S('Electrical requirements and operating envelope','dc',[
['18–42 V bus','6S–10S packs. The preferred design point is 8S: 29.6 V nominal, 33.6 V fully charged.'],
['25 / 40 Arms targets','Passive cooling / a defined thermal solution. Phase current differs from battery current.'],
['80 A peak is a future target','At most 2 s, subject to qualification. Initial +60 A protection prevents treating this as an enabled rating.']
],'60 V MOSFET absolute maximum requires margin for regeneration and switching overshoot.',
'The design constraints specify 25 Arms free-air, 40 Arms with a defined heatsink or forced airflow, and 80 A peak for no more than two seconds. These refer to motor phase current. They are not demonstrated ratings. An 80 A instantaneous peak cannot be commissioned while a +60 A comparator trip is active. The normal operating bus is approximately 18–42 V, with 10S support conditional on measured switching and braking performance. Capacitor voltage ratings do not raise the permissible MOSFET voltage. Source: DESIGN_CONSTRAINTS.md, Electrical rating target, and DESIGN_REVIEW_REV_A.md, operating envelope.');
S('System architecture and FOC signal flow','overview',[
['Local current control','Shunts measure phase current. The MCU uses rotor position and current feedback to calculate PWM.'],
['Outer motion loops','Velocity and position loops set the requested torque-producing current. CAN coordinates modules.'],
['Integrated control, external power','U301 combines the MCU, driver and analog resources. External MOSFETs set power-stage capability.']
],'Position feedback + phase current + synchronized PWM form the local control loop.',
'Field-oriented control transforms measured phase currents into a rotor-related coordinate system. Current regulators control torque-producing and field-related components, then modulation generates complementary PWM. The position sensor provides the rotor-angle reference. Integration reduces component count and pin-level interconnects, while external MOSFETs allow package and loss selection. This is an explanation of the intended control architecture, not a claim that firmware already implements it. Sources: DESIGN_CONSTRAINTS.md, Fixed architecture, and FIRMWARE_BRINGUP_CONTRACT.md.');
S('Power domains and operating modes','mux',[
['Control power survives USB service','5V_BAT and 5V_USB feed TPS2121. 5V_SYS feeds the external 3.3 V LDO.'],
['Gate power follows VM','The internal STSPIN buck generates VCC independently of the 3.3 V control rail.'],
['VM return requires reinitialization','USB can keep the MCU alive while the gate driver loses power. Restore VCC settings and protections before torque.']
],'USB alone powers logic and sensors. It does not energize VM, VCC or either power switch stage.',
'The external logic rail supplies the embedded MCU, sensor interfaces, CAN and service bridge. The gate-driver rail depends on VM, so USB-only operation cannot drive the inverter or brake. Both input supplies may be attached because the mux provides reverse-current blocking. On VM loss, firmware invalidates motor state and clears torque commands. On return it repeats the driver setup rather than continuing from a stale command. Source: DESIGN_CONSTRAINTS.md, Auxiliary power architecture, and FIRMWARE_BRINGUP_CONTRACT.md, Runtime rules.',{table:[['Supply state','Logic','Power stage'],['Battery only','5V_BAT selected','Available after setup'],['USB only','5V_USB selected','VM / VCC absent'],['Both valid','USB preferred','Available after setup'],['VM returns','MCU may stay alive','Reinitialize before arming']],smallImage:true});
S('Battery entry and DC-link capacitance','dc',[
['2040 µF bulk capacitance','C101–C103 are 680 µF / 63 V each. The bank buffers short bus-energy changes.'],
['Several capacitor scales','4.7 µF, 100 nF and 10 nF bypass paths support progressively faster current changes.'],
['Ripple rating can be limiting','5.07 Arms is the summed 100 kHz nameplate rating. Actual sharing, frequency and temperature change the usable margin.']
],'E = ½CV² = 1.80 J at 42 V',
'The parallel electrolytics provide 2.04 mF nominal capacitance. At 42 V the stored energy is 0.5 × 0.00204 × 42² = 1.799 J. This is much smaller than the example mechanical braking energy later in the deck, so the capacitor bank cannot replace a brake resistor. Bulk ESR contributes damping and heating. Ceramic capacitance falls with DC bias and its effectiveness depends on loop inductance. The nameplate ripple sum is not the actual permissible motor phase current. Measure capacitor current and case temperature during the load ramp. Sources: schematic page 2, BOM C101–C106, electrical_calculations.json bus section, and DESIGN_REVIEW_REV_A.md.');
S('Inrush, discharge and input damping','damping',[
['Bidirectional battery path','Regenerated current can return to a suitable battery. Rev A omits reverse-polarity protection and active precharge.'],
['470 kΩ is a slow bleeder','R101 dissipates only 3.75 mW at 42 V. Bulk-only discharge has an approximately 16-minute time constant.'],
['Damping remains unpopulated','D101 and R102/C107 need cable and hot-plug measurements before selecting values.']
],'τ = 470 kΩ × 2040 µF = 959 s; external precharge/current limiting is required for first tests.',
'The bulk-only RC estimate excludes the converters and other attached loads, which can shorten measured discharge. One time constant leaves roughly 37 percent of the starting voltage, so the board is not discharged after 16 minutes merely because that is the time constant. Hot-plug cable inductance and low-ESR capacitance can produce a bus overshoot. An arbitrary input inductor can worsen this resonance. D101 is a DNP TVS placeholder. R102/C107 form a DNP series RC damping branch. TVS pulse clamping, inrush limiting and sustained regenerative dissipation are different functions. Source: schematic page 2 and DESIGN_CONSTRAINTS.md, Power entry, long cables, and inrush.');
S('Bus divider and powered-off ADC isolation','divider',[
['A 21:1 voltage scale','R103 + R104 = 540 kΩ. R105 = 27 kΩ. Splitting the upper leg distributes voltage stress.'],
['267 µs nominal filtering','R106 = 1 kΩ and C108 = 10 nF. Divider impedance contributes most of the time constant.'],
['U602 isolates the live divider','The capacitor sits after isolation. Enable the mux and wait at least 2 ms before trusting VM.']
],'VADC = VM / 21 = 2.00 V at 42 V; VM sensing is invalid whenever the feedback mux is disabled.',
'RTH = 540 kΩ parallel 27 kΩ = 25.714 kΩ. Including the series 1 kΩ gives τ = 267.14 µs, neglecting the much smaller mux on-resistance. Two milliseconds corresponds to approximately 7.49 time constants, giving about 0.056 percent residual ideal settling error. At 60 V the divider would produce 2.857 V, a headroom calculation rather than permission to operate at 60 V. Both channel-4 mux inputs connect to the divided bus, so position-source selection does not alter the divider scale. Disabling the common mux enable still removes VM sensing. Sources: schematic pages 2 and 10, electrical_calculations.json bus section, firmware contract.',{second:'vmmux'});
S('Battery-to-5 V buck converter','buck',[
['LMR36510F at 400 kHz','A switching converter avoids dissipating the large VM-to-5 V drop as heat. Forced PWM keeps predictable switching at light load.'],
['22 µH inductor','Nominal ripple is 0.41–0.50 A peak-to-peak over 18–42 V for approximately 5 V output.'],
['44 µF nominal output bank','Two 22 µF ceramics support load transients. Effective capacitance and regulator stability still require review.']
],'VOUT = 1.00 × (1 + 100 kΩ / 24.9 kΩ) = 5.016 V',
'U201 is LMR36510FADDAR, the forced-PWM 400 kHz variant. R201/R202 set the adjustable output. For an ideal buck in continuous conduction, ΔIL = VOUT(1 − VOUT/VIN)/(L fSW). At 18 and 42 V using 5.016 V, 22 µH and 400 kHz this gives approximately 0.411 and 0.502 A peak-to-peak. At a 1 A average load the nominal inductor peak is about 1.25 A, before tolerances or transients. The 2.75 A inductor rating is not a guarantee of regulator current capability. Low oscillator frequency and reduced inductance increase ripple. C203 = 100 nF supports the buck bootstrap, C204 = 1 µF bypasses the internal bias rail, C201/C202 bypass VM, and C205/C206 support output load transients. Sources: schematic page 3, local LMR36510 datasheet Device Comparison and switching-frequency specification; Wurth 74437349220 datasheet.');
S('USB-priority power mux','mux',[
['Different priority divider ratios','15 kΩ / 5.10 kΩ on battery and 10 kΩ / 5.10 kΩ on USB set USB preference.'],
['Defined input thresholds','21 kΩ / 5.10 kΩ dividers set approximately 5.43 V overvoltage thresholds.'],
['Current limit and soft start','80.6 kΩ sets approximately 1.5 A. C209 = 100 nF controls startup slew.']
],'At 5 V: PR1 = 1.269 V and CP2 = 1.689 V, so valid USB takes priority.',
'TPS2121 isolates the sources and selects a preferred input. PR1 = 5 × 5.10/(15.0+5.10) and CP2 = 5 × 5.10/(10.0+5.10). The recorded OV setting uses a nominal 1.06 V reference: 1.06 × (21+5.10)/5.10 ≈ 5.425 V. These are nominal values, and the full datasheet threshold and resistor tolerances must be included in qualification. C210 = 22 µF and C211 = 100 nF bypass the mux output. R215 = 10 kΩ pulls its status signal to 3V3. Soft-start timing depends on the device SS behavior and output loading. The 1.5 A setting does not authorize drawing that current from USB. Sources: schematic page 3, DESIGN_REVIEW_REV_A.md and TPS2121 datasheet, priority, OV, ILM and SS sections.');
S('3.3 V LDO and control-power budget','ldo',[
['TLV75533P supplies the logic rail','The external 500 mA regulator supports both battery and USB operation while bypassing the STSPIN internal 3.3 V regulator.'],
['250 mA planning allowance','The recorded CAN-fault allowance raises this to 320 mA. External feedback is limited to 25 mA.'],
['Thermal loss matters','At 5.25 V input, the LDO dissipates 0.488 W normally or 0.624 W at the fault allowance.']
],'PLDO = (VIN − 3.3 V) × ILOAD',
'The current budget allocates 100 mA for MCU/driver logic, 25 mA encoder, 10 mA IMU, 61 mA dominant CAN, 20 mA CP2102N, 25 mA external feedback, and 9 mA miscellaneous, totaling 250 mA. The normal budget contains planning allowances rather than a measured operating current. C212/C213 are 2.2 µF each and must retain sufficient effective capacitance for the LDO requirements. Linear regulation simplifies the rail and avoids an additional switching node, at the cost of heat. The DYD thermal pad connects to ground. Junction temperature depends on real copper and enclosure temperature. Sources: electrical_calculations.json logic_budget_mA, schematic page 3, TLV755P datasheet.');
S('MCU, clock, reset and SWD','clock',[
['24 MHz crystal, 7 pF load','Two 10 pF C0G capacitors contribute 5 pF series load, leaving approximately 2 pF for stray capacitance.'],
['Controlled reset and boot states','Reset pull-up/filter and BOOT0 defaults support predictable startup. PB8 shares the feedback index/Hall input.'],
['Debug and analog supplies','SWD remains available. Local bypassing serves VDD, VDDA and VREF+. VTREF is a sense connection.']
],'CL ≈ C1C2 / (C1 + C2) + Cstray',
'The 10 pF capacitors are starting values for a 7 pF crystal load, because two equal 10 pF capacitors contribute 5 pF in series. Pin, trace and package capacitance supplies the remaining assumed 2 pF. The oscillator must be verified for startup and frequency. R303 = 100 kΩ with C310 = 100 nF gives a nominal 10 ms external reset RC, although actual reset behavior includes device thresholds and internal circuitry. R304 = 1 kΩ limits LED current to roughly (3.3 − VF − VOL)/1000. R301/R302 are 0 Ω analog supply links with local 100 nF and 1 µF bypassing; they are not designed ferrite filters. PB3 is SPI SCK, so SWO is absent. The short R1001/button branch permits manual BOOT0 control, and the feedback mux isolates PB8 through reset. Sources: schematic page 4, BOM and firmware contract.',{second:'corepower'});
S('Gate-driver supply and 10 V selection','vcc',[
['8 V at reset, 10 V in operation','Firmware must restore the 10 V setting after every VM power-up.'],
['22 µH is a prototype substitution','L301 replaces the typical 18 µH example. Regulation and startup require measurement.'],
['10 µF reservoir + 100 nF bypass','C312/C313 supply fast gate and bootstrap demand locally. Brake-driver demand also loads VCC.']
],'6 × 56 nC × 20 kHz = 6.72 mA average gate-charge current',
'At 10 V that charge current corresponds to approximately 67.2 mW of gate-drive energy per second. It excludes quiescent driver current, conversion loss and the brake driver. The 56 nC figure is the CSD88599Q5DC maximum total gate charge at the datasheet 10 V, 30 V drain, 30 A conditions. Higher gate voltage can lower RDS(on), but increases charge energy and stress. Ten volts is the released starting point. D302 is the external catch diode for the STSPIN internal buck and C311 bypasses VM. The 22 µH choice must be judged with the STSPIN regulator behavior rather than treating it as the 400 kHz external buck. Sources: schematic page 5, DESIGN_REVIEW_REV_A.md; STSPIN32G4 DS13630 Rev 2, section 5.1.1; CSD88599Q5DC SLPS597D section 4.5.');
S('Three-phase inverter topology','inverter',[
['One dual MOSFET package per phase','Q401–Q403 each contain the high-side and low-side switches. Parallel packages are deferred.'],
['Complementary switching','The upper switch connects a phase to VM. The lower switch provides the lower rail path and synchronous freewheeling.'],
['Selection follows total loss','Conduction, switching, recovery and package thermal paths all matter alongside the 60 V rating.']
],'At VGS = 10 V, datasheet RDS(on) is 1.7 mΩ typical / 2.1 mΩ maximum at its stated conditions.',
'The paired package reduces interconnect length inside each half-bridge and supports a compact stage. All three phase outputs connect to J401. Inductive current continues during deadtime through appropriate body-diode paths, followed by synchronous conduction when the commanded MOSFET turns on. Both switches in one leg must never be on simultaneously. CSD88599 datasheet loss figures use a particular external driver and capacitor bank; this design uses STSPIN and different local capacitance, so those curves cannot directly establish the board rating. RDS(on) rises with temperature. The maximum value quoted on the slide applies to the datasheet 25 °C electrical test condition, VGS = 10 V and ID = 30 A. Sources: schematic page 6 and CSD88599Q5DC SLPS597D sections 4.3–4.5.');
S('Bootstrap operation and capacitor value','bootstrap',[
['C411 / C421 / C431 = 100 nF, 25 V','Each capacitor floats between BOOTx and OUTx. It charges while the phase is low.'],
['Gate-charge-only droop is 0.56 V','56 nC / 100 nF. Leakage, driver supply current and the 100 kΩ gate pull-down add charge demand.'],
['Use effective capacitance','A 50 nF effective value would double that droop to 1.12 V. Larger values also take longer to recharge.']
],'Ceff ≥ [Qg + (IHB + Ileak + VGS/RGS)tON + Qother] / ΔVallowed',
'When OUTx is low, the internal bootstrap diode charges the capacitor from VCC. When the high-side MOSFET turns on, OUTx rises and the capacitor keeps the high-side driver supply above that moving source. The capacitor voltage rating concerns the BOOT-to-OUT differential, while physical spacing also sees switch-node common-mode motion. The 56 nC charge figure is conservative at the TI datasheet test conditions but does not include all high-side supply consumption. A 100 kΩ gate-source resistor draws about 100 µA at 10 V, adding 5 nC over a 50 µs dwell, equivalent to 0.05 V on 100 nF. The allowable droop must retain both UVLO margin and adequate MOSFET enhancement. Actual effective capacitance depends on the selected capacitor MPN, bias and tolerance. Sources: schematic page 6, STSPIN32G4 local DS13630 Rev 2 sections 5.2.4–5.2.6, TI CSD88599Q5DC charge specifications.');
S('Bootstrap refresh and PWM limits','phase',[
['20 kHz gives a 50 µs period','Low-side time must support both bootstrap replenishment and valid current sampling.'],
['Internal charging resistance matters','The local ST datasheet lists 100 Ω typical, 200 Ω maximum. With 100 nF, the simple RC scale is 10–20 µs.'],
['No static high-side 100% duty','Precharge at startup and enforce refresh intervals. Determine the modulation limit from measured BOOT–OUT voltage.']
],'An RC illustration: 90% recharge from empty takes about 2.3τ = 23–46 µs.',
'The simple RC calculation illustrates startup charging, not a required recharge duration for every PWM cycle. Periodic top-up begins from an already charged capacitor and the device diode current characteristic is nonlinear. At 95 percent duty and 20 kHz, the nominal low interval is only 2.5 µs before deadtime and other constraints. This cannot be assumed adequate from a 0.56 V droop calculation. For an approximate resistive recharge model, the fraction of a voltage deficit restored in t is 1 − exp(−t/RC). In 2.5 µs this is about 22 percent at 100 Ω and 12 percent at 200 Ω. Measure under the actual load and duty sequence. C312 must also supply bootstrap startup demand. External bootstrap diodes would be a design change and are not fitted in this release. Source: local STSPIN32G4 DS13630 Rev 2 electrical characteristics and sections 5.2.4.1–5.2.4.2.');
S('High-side and low-side gate resistor choices','gates',[
['4.7 Ω at GH, 0 Ω at GL','R411/R421/R431 slow the high-side edge. R412/R422/R432 retain a strong low-side gate connection.'],
['The asymmetry follows TI guidance','TI recommends 4.7–10 Ω on GH and a direct GL connection to reduce parasitic capacitive turn-on.'],
['Tune with the actual driver and PCB','Larger resistance can reduce ringing but increases switching loss. A 100 kΩ pull-down establishes the unpowered default.']
],'Ig,Miller ≈ (Vdrive − Vplateau) / (Rdriver + Rexternal + Rgate); tMiller ≈ Qgd / Ig',
'TI SLPS597D section 5.8.1.1 supports the GH/GL starting choices for its power block. A zero-ohm external resistor does not mean zero gate-loop impedance: the STSPIN output stage, internal MOSFET gate resistance and PCB inductance remain. The TI datasheet lists internal gate resistance around 0.9 Ω typical and 1.8 Ω maximum, and Qgd around 7 nC typical at its specified test condition. For illustration, 0.1 A Miller current with 7 nC would imply about 70 ns, but no actual gate current is established by this estimate. Measure VGS and VDS with suitable probes while checking loss and temperature. The 100 kΩ pull-downs cannot substitute for active sink current during a fast Miller event. Each gate has one series resistor for both directions; there are no separate turn-on and turn-off diode paths. Sources: schematic page 6, TI CSD88599Q5DC SLPS597D sections 4.5 and 5.8.1.1.');
S('Deadtime, interlocking and switching losses','gate',[
['Start at 500 ns deadtime','The MCU begins with conservative timing at 20 kHz. Driver interlocking provides a separate layer.'],
['Longer deadtime also costs energy','Inductive current uses body diodes during the interval, affecting loss and low-current distortion.'],
['Gate speed is a measured tradeoff','Propagation delay, Miller behavior and temperature determine the minimum safe setting.']
],'Pcond ≈ Irms²RDS(on,T); Psw ≈ ½VDSID(tr + tf)fsw',
'Conduction calculations must include which MOSFET conducts, the phase waveform and PWM duty. As a scale example only, 40 Arms through 2.1 mΩ for full conduction gives 3.36 W before temperature correction; it is not automatically the dissipation of each of six devices. The switching-loss equation assumes simple overlapping voltage/current transitions. Reverse recovery, output-capacitance energy and commutation details can add significant loss. A 30 kHz alternative would increase frequency-proportional losses by about 50 percent if transition conditions stayed equal. The internal minimum deadtime and interlock settings must agree with MCU complementary PWM. Sources: firmware contract, schematic pages 5–6, STSPIN32G4 sections 5.2.1–5.2.3, TI switching data.');
S('Local capacitors, ringing and snubbers','localcaps',[
['Two different return points','C412 = 1 µF to GND. C415 = 10 nF directly to the source above the shunt.'],
['R415 / C413 are DNP','A series RC branch can damp phase-node resonance after measurement identifies the ringing.'],
['42 V and regeneration need attention','TI calls for RC snubbers in its 42–54 V input region. This board has no fitted phase snubber yet.']
],'Commissioning target: measured VDS peaks below 55 V, with margin to the 60 V absolute limit.',
'TI identifies current-shunt and PCB inductance as a ringing source and recommends a local 10 nF VIN-to-source capacitor, matching C415/C425/C435. The 1 µF capacitor returns to board ground below the shunt, so the two paths have different loop geometry. A measured resonance f0 and a repeat measurement f1 after adding known capacitance Ctest permit an estimate Cpar = Ctest/[(f0/f1)² − 1], assuming inductance is unchanged. Then Lpar = 1/[(2πf0)²Cpar]. Damping resistance starts near the resonant impedance, followed by tuning and power verification. P ≈ Csnub V² fsw is a first loss estimate. The TI 42–54 V snubber recommendation is a real qualification gap because a fully charged 10S pack and regeneration reach this region. No component is silently changed here. Source: TI SLPS597D recommended operating conditions and section 5.8.1.1; released BOM and firmware contract.');
S('Three-shunt current sensing','shunt',[
['0.5 mΩ per phase','R416/R426/R436 produce 20 mV at 40 A and 40 mV at 80 A.'],
['Kelvin pads measure the element','Force current uses pads 1/4. Sense pads 2/3 connect only to the amplifier network.'],
['Signal size versus loss','Lower resistance saves power but makes offsets and noise more significant. Three shunts improve sensing options.']
],'Pshunt = I²R = 0.8 W at 40 Arms; 3.2 W instantaneously at 80 A',
'A four-terminal device separates the sense connection from the high-current solder and copper voltage drops. All three channels use the same value and amplifier network. Shunt pulse capability depends on duration and terminal temperature; the instantaneous 3.2 W calculation alone does not qualify the two-second peak. A three-shunt architecture still samples through available low-side conduction intervals. Near extreme modulation those intervals can be too short, so firmware must schedule conversions, account for settling and reconstruct a third phase when appropriate. Source: schematic page 6, electrical_calculations.json current section, BVR shunt documentation referenced in DESIGN_REVIEW_REV_A.md.');
S('Current-amplifier gain, bias and tolerance','current',[
['Gain 28, centered at 1.65 V','1 kΩ input resistors and 28 kΩ feedback provide 14 mV/A with the 0.5 mΩ shunt.'],
['Matched 0.1% resistor network','Two 56 kΩ resistors form an equivalent 28 kΩ bias source at VREF/2.'],
['Bipolar measurement with headroom','−80 A, zero and +80 A correspond nominally to 0.53 V, 1.65 V and 2.77 V.']
],'VOUT = VREF / 2 + 28(VSENSE+ − VSENSE−)',
'For phase U, R417/R418 are 1 kΩ, R419 is 28 kΩ, and R410/R441 are 56 kΩ. The bias Thevenin resistance equals the feedback resistance, giving the intended differential transfer with a midpoint offset. The resistor-only zero-current range is 1.6436–1.6564 V, or about ±0.46 A when divided by 14 mV/A. Device offset, finite common-mode rejection, reference/ADC error and temperature add to that estimate. A 12-bit ADC at 3.3 V has an ideal code width near 0.806 mV, equivalent to 57.5 mA at 14 mV/A, before noise and calibration. C414/C424/C434 are 47 pF compensation options but DNP. Calibration must use the actual channel with PWM off. Sources: schematic page 7 and released calculation JSON.');
S('Sampling and hardware overcurrent shutdown','current',[
['Comparators see the input node','COMP1/2/4 observe the biased op-amp positive inputs, before amplification.'],
['+60 A is an initial trip target','The nominal input is 85.86 mV, about DAC code 107. Offset and DAC errors can move the actual trip substantially.'],
['Timer break acts after configuration','The hardware path can stop PWM without a CPU interrupt. Negative-current limits also need ADC supervision.']
],'VCOMP ≈ (56 × 0.0005 × I + 3.3) / 58',
'This formula assumes the negative Kelvin terminal remains near analog ground and uses the released 1 kΩ / 56 kΩ network. At +60 A the numerator is 4.98 V-equivalent divided by 58, giving 85.862 mV. A 12-bit 3.3 V DAC gives about code 107. The slope at that node is only 0.4828 mV/A, so a 1 mV aggregate offset would imply roughly 2.1 A trip movement. This is why the threshold cannot be advertised as precise without calibration. COMP1 uses DAC3 channel 1 and COMP2/4 use DAC3 channel 2 according to the firmware contract, to be confirmed in the exact configuration. U and W share ADC1, so acquisition is not simultaneous on every phase. Valid low-side windows, blanking and op-amp settling govern sampling. Source: FIRMWARE_BRINGUP_CONTRACT.md, Analog/peripheral map.');
S('VDS fault detection and SCREF','scref',[
['0.30 V nominal reference','R310 = 100 kΩ and R311 = 10 kΩ divide the 3.3 V rail.'],
['Local reference filtering','R312 = 1 kΩ and C314 = 10 nF filter SCREF. Divider impedance makes τ approximately 101 µs.'],
['An additional short-circuit mechanism','VDS depends on current, RDS(on), temperature and gate enhancement. It cannot set a precise phase-current limit.']
],'VSCREF = 3.3 × 10 / 110 = 0.30 V',
'The reference Thevenin resistance is 100 kΩ parallel 10 kΩ = 9.091 kΩ. Adding R312 produces approximately 100.91 µs with 10 nF. The driver monitors an on-state device and applies its deglitch behavior before latching a VDS fault. Startup, minimum gate enhancement, UVLO and the VDS detection timing matter. The shunt comparator and VDS mechanisms are complementary because their measurement points and errors differ. A simple SCREF/RDS(on) quotient would miss the protection offsets, temperature changes and dynamic behavior. Source: schematic page 5 and STSPIN32G4 local DS13630 Rev 2 section 5.2.5.');
S('Phase temperature measurement','ntc',[
['Three 10 kΩ NTCs, B3380','TH701–TH703 monitor local phase heating. Each uses a 4.7 kΩ pull-up.'],
['Sensitivity shifts toward warm operation','The lower fixed resistor improves the useful divider span at elevated temperature. Each ADC has 1 kΩ / 10 nF filtering.'],
['Use the hottest valid sensor','An open NTC reads high, a short reads low. Sensor temperature lags MOSFET junction temperature.']
],'VADC = 3.3 × RNTC / (4.7 kΩ + RNTC)',
'The nominal beta approximation is R(T) = 10000 exp[3380(1/T − 1/298.15)] with T in kelvin. At 25 °C it gives 10 kΩ and 2.245 V. Approximate values at 60, 90 and 110 °C are 3.04 kΩ / 1.30 V, 1.32 kΩ / 0.72 V, and 0.81 kΩ / 0.49 V. These are model values, not a calibrated transfer. Maximum divider self-heating occurs near RNTC = 4.7 kΩ: PNTC,max = 3.3²/(4×4700) ≈ 0.58 mW. Convert that to temperature error with the selected device dissipation constant and mounting conditions. Filter impedance also includes the divider parallel resistance, so the time constant changes with temperature. Source: schematic page 7, BOM NCP18XH103F03RB and design constraints.');
S('Brake-chopper topology and gate drive','brake',[
['A local energy dump','The external resistor connects from VM to BRK_SW. Q501 switches its return to ground.'],
['100 V MOSFET and dedicated driver','CSD19531Q5A provides added voltage margin. UCC27517A drives it from VCC.'],
['A controlled gate loop','4.7 Ω gate resistor, 10 kΩ pull-down, 12 V gate clamp and local 1 µF + 100 nF bypass.']
],'D504 recirculates brake-lead inductance. The external resistor absorbs sustained regenerative energy.',
'The low-side chopper uses a dedicated gate driver because a 3.3 V MCU output alone would not adequately drive the selected power MOSFET. Q501 is rated 100 V, offering more voltage margin than the 60 V inverter packages. Its suitability also depends on switching loss, repetitive pulse SOA and temperature. R503 controls edge speed, R504 establishes gate off, and D501 clamps the gate. Both brake-resistor wires can carry bus voltage. D504 is a 100 V / 5 A flyback diode connected across the external resistor path and catches lead inductance when the switch turns off. It is not the main regenerative dump. Firmware and comparator commands are combined by D502/D503. Source: schematic page 8 and DESIGN_REVIEW_REV_A.md, Brake energy and overvoltage.');
S('Brake resistor power and energy sizing','brake',[
['10 Ω at a 48 V calculation point','The resistor draws 4.8 A and dissipates 230.4 W when fully on.'],
['A stop can contain 219 J','Example: J = 0.01 kg·m², speed = 2000 rpm, final speed = zero.'],
['Power and pulse energy are separate','The example requires ≥250 W with the specified heatsink and independently qualified 500 J over 5 s.']
],'I = V/R; P = V²/R; E = ½J(ωstart² − ωend²)',
'Angular speed is 2000 × 2π/60 = 209.44 rad/s, so the rotational energy is 0.5 × 0.01 × 209.44² = 219.32 J. The 500 J over five seconds requirement provides example energy margin, but resistor pulse capability must come from its own datasheet and mounting conditions. Repeated stops set average thermal demand and cooldown needs. Gravity or an externally driven motor can add energy indefinitely, unlike the finite inertia example. At 48 V, the resistor instantaneous power is 48²/10 = 230.4 W. At 43 V it is 184.9 W, so available braking rate also changes with bus voltage. The 48 V example is a sizing point, not a sustained operating rating. An open or missing resistor removes braking and is not automatically detected. Source: electrical_calculations.json brake section and firmware contract.');
S('Independent overvoltage brake command','brakeov',[
['TLV3012B with positive feedback','Three 150 kΩ upper resistors, 12.7 kΩ lower resistor and 1 MΩ hysteresis feedback.'],
['45.92 V on / 44.21 V off','Recorded nominal thresholds. Corner ranges widen to 44.19–47.51 V rising and 42.58–45.96 V falling.'],
['Firmware brakes earlier','43 V is the initial 10S firmware setting. The hardware OR path can act during MCU reset if 3V3 and VCC remain present.']
],'The threshold calculation excludes wiring inductance and dynamic bus overshoot.',
'At comparator switching, the sense node reaches the applicable reference plus input offset/hysteresis. With upper resistance RU = 450 kΩ, lower RL = 12.7 kΩ and feedback RF = 1 MΩ, KCL gives VM = Vtrip(1+RU/RL+RU/RF) − VOUT(RU/RF). A change in comparator output shifts the next threshold, preventing chatter. The published nominal values also include the comparator internal hysteresis model used by the project calculation. R506–R508 split bus-voltage stress. C504 = 1 nF filters the comparator input, with an approximate passive Thevenin time constant of 12.2 µs when the rails/output are stiff. D502/D503 diode-OR the PWM and hardware commands into the driver. Missing VCC or 3V3 disables the backup. Source: schematic page 8, electrical_calculations.json and TLV3012B datasheet.');
S('Onboard magnetic encoder','encoder',[
['AS5047P position feedback','SPI provides absolute angle. ABI outputs provide timer-compatible incremental feedback through the selector.'],
['Local supply and edge control','100 nF + 1 µF bypassing. 33 Ω ABI and MISO series resistors are signal-integrity starting values.'],
['Mechanical alignment is essential','Shaft magnet placement, offset calibration and error checks determine usable angle accuracy.']
],'One sensor supports absolute SPI angle and incremental A/B/index paths.',
'U601 shares SPI3 with the IMU but has its own chip select. R309 = 10 kΩ holds encoder CS high through reset. R601–R603 are 33 Ω on ABI outputs and R611 is 33 Ω on encoder MISO. These series resistors limit edge excitation with trace/load capacitance and should be placed at the source. They are not voltage translators and their numeric cutoff cannot be assigned without a real load model. TEST is held low for normal operation. Encoder-to-shaft alignment and magnetic conditions require mechanical design and calibration. The firmware contract specifies SPI mode 1. Sources: schematic page 9, BOM, pin plan and AS5047P manufacturer datasheet linked in the schematic.');
S('IMU and shared SPI bus','imu',[
['BMI323 supplies motion telemetry','Its accelerometer/gyroscope data complements rotor feedback and uses separate interrupt pins.'],
['A shared bus saves MCU pins','SCK/MOSI have 22 Ω source resistors. Each peripheral MISO has its own 33 Ω series resistor.'],
['SPI modes differ','Encoder mode 1, BMI323 mode 0 or 3. Both chip selects must be high while the MCU changes mode.']
],'Keep sensor transactions separate and verify MISO release by the inactive device.',
'U701 uses two local 100 nF supply bypass capacitors, a 10 kΩ CS pull-up and two interrupt connections. R313/R314 belong close to the MCU SCK/MOSI outputs. R714 belongs at the IMU MISO output. The protocol switching rule prevents one sensor interpreting a mode transition while selected. Sensor placement must avoid high-current magnetic fields, strong thermal gradients and switch-node coupling. Mark sensor axes on the board and account for mounting orientation in software. IMU motion sensing is not a replacement for the rotor position needed by the motor-control loop. Sources: schematic page 9, firmware contract and BMI323 manufacturer datasheet linked in the BOM.');
S('External feedback selection and protection','feedback',[
['Onboard ABI or external Hall/encoder','TMUX1574 routes a selected source to the shared TIM4 inputs.'],
['0–3.3 V signal contract','100 Ω input series resistors and ESD protection support the interface. Optional 10 kΩ pulls serve open-drain Hall outputs.'],
['Reset isolation has two purposes','It protects PB8/BOOT0 state and disconnects live VM sensing from the unpowered MCU.']
],'25 mA external supply allowance; R604 = 0 Ω is a link, not a current limiter.',
'J601 provides 3V3 output, ground and three feedback signals. It is not a power injection point. D601 uses a separate floating ESD rail with C604 = 100 nF to avoid a direct clamp path into 3V3 when board power is absent. External input levels must still remain within 0–3.3 V. The TMUX is not a level translator and does not switch sensor power. R305 holds enable inactive at reset and R306 selects the onboard path by default. R307 holds the shared PB8/BOOT0 input low. R608–R610 are DNP 10 kΩ pull-ups only for an appropriate open-drain external interface. Disable torque before source changes, and revalidate VM after the shared enable settles. Sources: schematic page 10 and FIRMWARE_BRINGUP_CONTRACT.md.');
S('CAN physical interface','can',[
['TCAN3413 on the 3.3 V rail','The transceiver connects local FDCAN to a protected differential daisy-chain bus.'],
['Standby and recessive defaults','10 kΩ pulls hold STB and TX high until firmware configures the interface.'],
['Optional 120 Ω end termination','R802 and JP801 are DNP. Fit and close only at a physical bus end.']
],'J801/J802: 1 GND, 2 CANL, 3 CANH, 4 shield/drain. Pin 4 carries no supply.',
'C801/C802 provide 100 nF and 1 µF decoupling near U801. D801 is the CAN ESD part and belongs near the connectors. R803/R804 are zero-ohm series links, not termination. The two connectors expose the same bus for daisy chaining. Exactly appropriate end termination and short stubs are necessary for signal integrity. The interface is unisolated, so system ground offsets and cable shielding require attention. Bus rate depends on transceiver/controller settings, cable and topology; this deck does not assert a qualified rate. Source: schematic page 11, TCAN3413 datasheet and DESIGN_REVIEW_REV_A.md control-power and interface limits.');
S('USB-C service and UART bridge','usb',[
['5.1 kΩ CC resistors','The connector exposes USB service power and data. USBLC6 protects the data pair.'],
['CP2102N uses external 3.3 V','VDD and VREGIN share one rail in bypass mode. UART TX/RX use 100 Ω series resistors.'],
['Source must permit ≥500 mA','There is no USB-PD negotiation or pre-enumeration/suspend load shedding. Reset and BOOT0 remain manual.']
],'The 22.1 kΩ / 47.5 kΩ divider senses USB presence separately from bridge power.',
'R203/R204 are 5.1 kΩ CC pull-downs. USB VBUS feeds the control-power mux, while CP2102N uses 3V3 on both supply pins, avoiding a split-rail UART sequencing problem. At 5 V USB, the nominal VBUS-detect divider produces 5 × 47.5/(22.1+47.5) ≈ 3.412 V at the specific CP2102N VBUS detection pin; that is not a generic MCU ADC input. The manufacturer circuit and limits apply. C901/C902 and C903/C904 provide 4.7 µF plus 100 nF for each supply group. UART labels use the MCU perspective. The fitted shield link is R205 = 0 Ω, and C207 is a DNP 4.7 nF / 2 kV alternative. Source: schematic page 12, CP2102N local datasheet Rev 1.5 figure 2.3 and QFN20 pin table, firmware contract.');
S('Reset states and fault response','brakecontrol',[
['Inverter defaults inactive','Firmware must explicitly configure sensing, break paths and the driver before arming.'],
['Different protections have dependencies','Timer-break comparison needs configuration. OV braking needs its supplies and a suitable external resistor.'],
['A fault requires deliberate recovery','Latch inverter off, invalidate stale commands and recheck power, feedback and temperatures.']
],'An unpopulated TVS or snubber footprint provides no fitted transient protection.',
'Reset and erased-MCU states keep PWM inactive, the feedback mux disabled and CAN in standby. The hardware overvoltage comparator can assert independently of CPU execution when the supply rails are present. A comparator break, driver VDS fault, feedback loss, implausible temperature or VM fault must inhibit torque. VM returning while USB maintains the MCU is particularly important because driver registers and VCC configuration may have reset independently. Automatic restart after such events is prohibited by the firmware contract. Source: DESIGN_REVIEW_REV_A.md, Fault and startup disposition, and FIRMWARE_BRINGUP_CONTRACT.md.',{table:[['Event','Required response'],['Reset / erased MCU','Keep inverter PWM inactive'],['VM disappears / returns','Clear torque, reinitialize driver'],['Current / VDS fault','Latch off, investigate before rearm'],['Feedback / NTC invalid','Inhibit torque'],['Regeneration, supply cannot sink','Use qualified local energy dump']],smallImage:true});
S('Layout requirements behind the schematic','phase',[
['Minimize the switching loop','Place local ceramics, MOSFETs and source return close together. Keep bootstrap and gate paths short.'],
['Separate force and sense paths','Kelvin pairs must not share motor-current copper. Keep analog nodes away from switch-node electric fields.'],
['Thermal pads have electrical meaning','The CSD88599 exposed VIN pad is live. Q501 and LDO pads require their exact package patterns.']
],'Component values depend on the parasitic inductance and thermal paths created by the PCB.',
'The 10 nF capacitor returns above the current shunt and the 1 µF capacitor returns to ground, so layout must preserve the intended local loop. Gate resistors belong at MOSFET gate pins. The NTC must couple thermally without introducing a signal path on the switch-node island. The inductor manufacturer specifies a central copper keepout. The DYD LDO thermal pad is ground, whereas the phase power block thermal VIN pad is at bus potential. Brake leads must remain short and appropriately rated. Footprint compatibility cannot be inferred from package outline alone. The current release supplies resolved footprints, but PCB placement, routing, DRC and thermal qualification remain future work. Sources: PCB_LAYOUT_HANDOFF.md and PCB_LAYOUT_GUIDELINES.md.');
S('Startup and low-energy commissioning','debug',[
['Verify logic power first','Check rails, source priority, backfeed and reset defaults. Program and retain recovery through SWD.'],
['Prove protection before raising power','Calibrate ADCs and current offsets. Demonstrate timer break, VDS faults and hardware braking.'],
['Begin unloaded and current-limited','18 V, 1–2 A current command, 20 kHz, 500 ns deadtime. Inspect gates and bootstrap voltage before increasing load.']
],'Voltage and current increase only after waveform, fault-response and thermal checks pass.',
'The firmware contract requires explicit arming with fresh commands, no automatic stale-command restart, feedback mux enable followed by at least 2 ms settling, ADC/op-amp calibration and comparator/DAC setup before PWM. Then configure STSPIN interlocking, protection and 10 V VCC, check READY/NFAULT and verify temperature and bus plausibility. Test battery-only, USB-only and both connection orders with current limiting and external precharge. Install the qualified brake resistor before regenerative operation. Use appropriate differential/isolated probing for switching nodes rather than connecting an earth-referenced probe ground to a phase. This is a commissioning sequence, not a record of completed measurements. Source: FIRMWARE_BRINGUP_CONTRACT.md, Hardware commissioning sequence.');
S('Choices requiring prototype measurements',null,[],
'Present values are starting selections. Measurements determine whether to keep or revise them.',
'Each row links a schematic value to a specific measurement rather than an unsupported claim of optimality. Bootstrap capacitance and maximum duty must be evaluated together. Gate resistance and snubber tuning need the actual PCB and probing arrangement. The final current envelope also depends on capacitor ripple, shunt limits and thermal paths. Source: DESIGN_REVIEW_REV_A.md and the corresponding module calculations.',{table:[['Choice','Present value','Measurement that decides'],['Bootstrap / maximum duty','100 nF per phase','BOOT−OUT minimum and recharge'],['Gate resistance','4.7 Ω GH / 0 Ω GL','VGS, VDS, switching energy and heat'],['Phase snubber / input damping','DNP tuning positions','Ringing and hot-plug response'],['VCC inductor','22 µH','Startup, regulation and ripple'],['Overcurrent threshold','Nominal +60 A','Calibrated trip and shutdown latency'],['DC-link bank','3 × 680 µF','RMS ripple and capacitor temperature'],['Brake resistor','10 Ω example','Energy, repetition rate and cooling']],tableFull:true});
S('Design conclusions and remaining decisions','overview',[
['The architecture is coherent','Integrated control, external power blocks, three shunts and local braking form a compact servo module.'],
['The operating envelope is still conditional','Capacitor ripple, bridge overshoot and heat govern the useful continuous current and maximum bus.'],
['Measurements close the design','Finalize gate timing, snubbers, brake energy and protection settings on the actual PCB.']
],'Connectivity review supports layout. Hardware qualification establishes usable ratings.',
'The main choices are an STSPIN32G4 with external 3.3 V logic power, 10 V gate drive, three 60 V power blocks, three low-side shunts, a local 100 V brake switch and configurable position feedback. The project reports zero schematic ERC violations and net/footprint consistency checks, which support proceeding to layout. These checks cannot prove switching safety, continuous current, thermal behavior or energy handling. The strongest open items are the DC-link ripple rating, snubber population around maximum bus voltage, bootstrap refresh margin and the reconciliation of the 80 A target with initial +60 A protection. Sources: SCHEMATIC_REDRAW_REVIEW.md and DESIGN_REVIEW_REV_A.md.');
S('A1. Bootstrap and gate-drive worksheet',null,[],
'Charge balance and recharge time must both pass at the selected modulation limit.',
'The worksheet distinguishes sourced part values from model inputs and measured quantities. Qg = 56 nC maximum is for 10 V drive at the TI stated 30 V/30 A conditions; Qgd = 7 nC is typical. Ceff cannot be finalized without a capacitor MPN and bias curve. At 20 kHz the period is 50 µs. Pull-down charge at 10 V is 5 nC over that full period. Adding that to Qg gives at least 61 nC before driver quiescent/leakage charge, corresponding to 0.61 V at nominal 100 nF. The startup RC estimate is illustrative. A VCC reservoir sharing charge with three initially empty 100 nF capacitors has ideal instantaneous sag 10×0.3/(10+0.3) ≈ 0.291 V when expressed in µF, before other effects. Source: local STSPIN32G4 DS13630 Rev 2 section 5.2.4 and CSD88599Q5DC SLPS597D charge table.',{tableFull:true,table:[['Input / result','Value','Status or implication'],['Qg at 10 V','56 nC maximum','TI test conditions: 30 V, 30 A'],['Qgd / internal gate R','7 nC typ / 0.9 Ω typ','Use actual driver strength and waveform'],['CBOOT nominal / effective','100 nF / MPN dependent','Bias, temperature and tolerance remain inputs'],['Gate-only droop','0.56 V at 100 nF','1.12 V if effective capacitance is 50 nF'],['100 kΩ pull-down demand','100 µA at 10 V','Adds 5 nC over 50 µs'],['Charging resistance scale','100–200 Ω','RC = 10–20 µs at 100 nF'],['90% empty-cap recharge','23–46 µs, ideal RC','Startup illustration, not a PWM guarantee'],['Final acceptance inputs','UVLO, IHB, leakage, tON','Measure minimum BOOT−OUT and VGS']]});
S('A2. Power and analog calculation summary',null,[],
'Nominal calculations use released values. Tolerance and operating conditions remain part of qualification.',
'The buck equation assumes continuous conduction and nominal switching frequency. LDO figures use the maximum-input example of 5.25 V. VM filter settling ignores the small mux on-resistance and ADC acquisition disturbances. Shunt loss at 80 A is instantaneous. The ideal current-code step is not an effective current resolution because noise and errors add. NTC figures use the simplified beta model. Additional passive rationale: reset R303/C310 nominal RC is 10 ms; LED R304 = 1 kΩ limits current using the actual LED VF and MCU VOL; 0 Ω analog links maintain separate routing options; 100 nF decouplers need placement at their supply pins. Sources: released calculation JSON, schematic pages 2–7 and LMR36510 data.',{tableFull:true,table:[['Network','Calculation','Nominal result'],['5 V buck divider','1 × (1 + 100/24.9)','5.016 V'],['Buck inductor ripple','VOUT(1−VOUT/VIN)/(Lf)','0.41–0.50 App at 18–42 V'],['Mux OV threshold','1.06 × (21+5.10)/5.10','5.43 V'],['LDO at 250 / 320 mA','(5.25−3.3) × I','0.488 / 0.624 W'],['VM divider and filter','VM/21; (25.714k+1k)×10n','2.00 V at 42 V; 267 µs'],['Shunt at 40 / 80 A','I² × 0.5 mΩ','0.8 / 3.2 W'],['Current gain / ideal code','28 × 0.5 mΩ; 3.3/4096/gain','14 mV/A; 57.5 mA/code'],['SCREF and filter','3.3/11; ((100k||10k)+1k)×10n','0.30 V; 101 µs']]});
S('A3. Brake threshold and energy worksheet',null,[],
'VM,trip = Vtrip(1 + RU/RL + RU/RF) − VOUT(RU/RF)',
'For the comparator network use RU = 450 kΩ, RL = 12.7 kΩ and RF = 1 MΩ. The comparator reference is nominally 1.242 V, with input offset and internal hysteresis included as appropriate. The project calculation records 45.919 V rising and 44.213 V falling and applies component corner allowances; it is not a dynamic switching simulation. Without both logic and gate supplies the brake cannot act. No fitted sensing proves resistor continuity. For the mechanical example, omega is 209.44 rad/s and energy is 219.32 J. At a repeated stop frequency r, average rotational energy dumping alone is approximately 219.32r watts, before gravity or externally supplied work. Source: electrical_calculations.json brake section and DESIGN_REVIEW_REV_A.md.',{tableFull:true,table:[['Quantity','Result','Interpretation'],['RU / RL / RF','450 kΩ / 12.7 kΩ / 1 MΩ','Reference and positive feedback set trips'],['Nominal rising / falling','45.92 V / 44.21 V','Includes project comparator model'],['Rising component corners','44.19–47.51 V','No dynamic bus overshoot included'],['Falling component corners','42.58–45.96 V','Do not assume fixed hysteresis at corners'],['10 Ω at 48 V','4.8 A; 230.4 W','Instantaneous fully-on stress'],['0.01 kg·m² at 2000 rpm','219.3 J','Rotational energy to zero speed'],['Example resistor requirement','≥250 W; 500 J over 5 s','Specified heatsink and pulse qualification'],['Missing resistor / missing rails','Braking unavailable','Installation and power dependencies']]});
S('A4. Schematic and component cross-reference',null,[],
'All 12 source sheets are represented. Full source citations and component detail are in the speaker notes.',
'The PDF pages are one-based. Image crops are from ShiroFOC_KiCad/outputs/ShiroFOC_Rev_A_Schematic.pdf. Phase mapping: U Q401 C411 R411/R412 R416 R417–R419 R410/R441 TH701; V Q402 C421 R421/R422 R426 R427–R429 R420/R442 TH702; W Q403 C431 R431/R432 R436 R437–R439 R430/R443 TH703. The 18 DNP positions are C107, C207, C413/C423/C433, C414/C424/C434, D101, JP801, R102, R415/R425/R435, R608/R609/R610 and R802. C107/R102 are input damping, D101 is input TVS, C207 is shield capacitance, phase R/C pairs are snubbers, C414/C424/C434 are amplifier compensation, R608–R610 are Hall pulls, and JP801/R802 are CAN termination. The full ungrouped released BOM carries assembly status and exact part numbers.',{tableFull:true,compact:true,table:[['PDF page / module','Main slides','Key references'],['1  System overview','1, 3, 36','Root sheet'],['2  Battery / DC link','2, 5–7','J101, C101–C108, R101–R106'],['3  Auxiliary power','4, 8–10','U201, U203, U204, L201'],['4  Controller / debug','11, 34','U301 A/B, Y301, J1001'],['5  Driver / VCC','12, 17, 22','U301 C, L301, R310–R312'],['6  Inverter','13–19, 33, 35','Q401–Q403, C411/421/431'],['7  Current / temperature','20, 21, 23','U301 D/E/F, TH701–TH703'],['8  Brake','24–26, 32','U501, U502, Q501, J501'],['9  SPI sensors','27, 28','U601, U701'],['10 Feedback selection','7, 29','U602, J601, D601'],['11 CAN','30','U801, D801, J801/J802'],['12 USB service','31','U202, U901, J201']]});
S('A5. Sources and unresolved evidence',null,[
['Project evidence','Current KiCad PDF/BOM, electrical calculations, design review, layout handoff and firmware contract.'],
['Manufacturer evidence','STSPIN32G4, CSD88599Q5DC and each supporting IC datasheet. Relevant sections and source paths accompany the slide notes.'],
['Unresolved hardware evidence','Bootstrap margin, capacitor ripple, switch-node overshoot, protection calibration, temperatures and braking remain prototype tests.']
],'No simulated or illustrative value in this deck represents a measured hardware result.',
'Primary local sources: ShiroFOC/ShiroFOC_KiCad/outputs/ShiroFOC_Rev_A_Schematic.pdf; ShiroFOC_Rev_A_BOM.csv; electrical_calculations.json; ShiroFOC/DESIGN_REVIEW_REV_A.md; DESIGN_CONSTRAINTS.md; FIRMWARE_BRINGUP_CONTRACT.md; PCB_LAYOUT_HANDOFF.md; PCB_LAYOUT_GUIDELINES.md; MCU_PINOUT_AND_INTERFACE_PLAN.md. The electrical review retains ST DS13630 Rev 2. The manufacturer currently serves Rev 3 dated 26 May 2026. Its revision history reports updates to Tables 2, 7, 15 and 27. The local Rev 2 basis is retained here for the existing design, and the complete updated operating/register/order-code details need reconciliation before firmware and procurement sign-off. Bootstrap operating principles were checked in current sections 5.2.4–5.2.4.2. https://www.st.com/resource/en/datasheet/stspin32g4.pdf . TI CSD88599Q5DC local SLPS597D, June 2024, sections 4.5 and 5.8.1.1: https://www.ti.com/lit/ds/symlink/csd88599q5dc.pdf . The TI snubber recommendation for 42–54 V and the released DNP state remain a stated qualification gap. Other manufacturer URLs are embedded in the released BOM and specific slide notes.');
